### ISSUE TITLE
Create 'ready check'

### ISSUE THREAD

**Issue by Callisto89** [KittenSoup/wardly#14]

**Comment by Callisto89** [comment]
- Knapp för att skicka pushnotis till de som anmält sig. Måste bekräfta att de är redo, annars kan den som är först i kölistan ta deras plats
- Automatisk 'ready check' 15 minuter före eventets starttid vid framtida event

**Comment by ProHugoLeet** [comment]
Created in Pull request #23

**Comment by ProHugoLeet** [comment]
1. App calls startReadyCheck(EventId)
2. Function in dataHandler calls backend startReadyCheck(EventId)
2a Backend checks if readyCheckTimeOut is running.
3a. Backend pushes readyCheckOpen(EventId) to all users in playerList for EventId.
3b. Backend starts readyCheckTimeOut(eventId) for 30s.

4. App pushHandler recieves readyCheckOpen(EventId)
5. App launches readyCheckPopup()
6. Player responds Ready/NotReady. 
7. App calls dataHandler call readyCheckAnswer(Ready/NotRead, eventId).
8. dataHandler calls backend readyCheckAnswer(Ready/NotReady, eventId).

for every readyCheckAnswer backend pushes update event to app. 
for every readyCheckAnswer backend checks if all players have answered.
9. App pushHandler recieves eventUpdated
(3b->) 10. readyCheckTimeOut answers NotReady for players that have not responded. (*Update shemesindex)

10. When last players answer; (Manual or by 30sec timeout)
if ready players =5
abort. 

if player in LastReadyCheck exists in playerlist - abort.

11. Move unready players to waiting list.
12. Add first player moved to LastReadyCheck. 
Move players from waitinglist to playerlist. 
Send readyCheckOpen(eventId) to players in PlayerList that are not ready.
Backend starts readyCheckTimeOut(eventId) for 30s. 
(4-9)

11. when aborted backend sends readyCheckComplete(eventId) to app.
12.  pushHandler recieves readyCheckComplete(eventId)
13. if eventplayers =5 send WOWOWOOo READY TO RUMBLEEEE 
if <5 send Not enough players :,(
